### ISSUE TITLE
TensorRT Runtime Error

### ISSUE THREAD

**Issue by chrisyoung2017** [AliCloud-PAI/dawnbench_infer#1]
Hi, it's seems that Ali-PAI made a lot of optimizations on inference,  but i encountered this error when I was running your code. i tried to fix it but failed, do you know the reason? Thanks so much.
![image](https://user-images.githubusercontent.com/40203755/74224935-b7f15880-4cf4-11ea-868c-b5cb281c5a6e.png)

**Comment by AliCloud-PAI** [comment]
> Hi, it's seems that Ali-PAI made a lot of optimizations on inference, but i encountered this error when I was running your code. i tried to fix it but failed, do you know the reason? Thanks so much.
> ![image](https://user-images.githubusercontent.com/40203755/74224935-b7f15880-4cf4-11ea-868c-b5cb281c5a6e.png)

**Comment by alibaba-yiwuyao** [comment]
> Hi, it's seems that Ali-PAI made a lot of optimizations on inference, but i encountered this error when I was running your code. i tried to fix it but failed, do you know the reason? Thanks so much.
> ![image](https://user-images.githubusercontent.com/40203755/74224935-b7f15880-4cf4-11ea-868c-b5cb281c5a6e.png)

Please make sure the Tesla T4 platform and CUDA driver version, Thanks.

**Comment by chrisyoung2017** [comment]
This is our env, we don't use docker to run your code, is it necessary?
![image](https://user-images.githubusercontent.com/40203755/74232303-77e5a200-4d03-11ea-9119-259d6aca0428.png)

**Comment by alibaba-yiwuyao** [comment]
The version of CUDA, cuDNN or TensorRT may be mis-matched, docker is preferred, thanks.

**Comment by chrisyoung2017** [comment]
it's works for me, thanks.
